:snake: Модуль для определения типа иглы и величины угла #27
AAIvanchenko/Diamond-needle-quality pull request #34
Opened 2021-11-07 21:45 UTC by rondi201

В данный модуль были добавлены функции для построения прямых
по границам иглы и расчёта статистик иглы. Так же к каждой
функции и к каждому классу была написана документация и
аннотация типов.

2021-11-08 04:06 UTC, redb0 requested changes

2021-11-08 04:06 UTC, redb0 commented on src/linear.py
> +    def sharpening_angle(self) -> float:
Вычисление угла между двумя прямыми лучше перенести в класс `Line`

2021-11-08 04:06 UTC, redb0 commented on src/linear.py
> +            y_list_new = np.hstack([y_list[:round(l*(loss_zone/2)):loss_ratio],
Лучше задать часто используемые индексы как `round(l*(loss_zone/2))` в виде отдельных переменных (констант)

2021-11-08 04:06 UTC, redb0 commented on src/linear.py
> +    def __init__(self, angle: float, area_triangle: float):
Добавить еще расстояние от точки пересечения двух прямых до кончика

2021-11-12 06:17 UTC, redb0 requested changes

2021-11-12 06:17 UTC, redb0 commented on src/contour.py
> +def read_path(name_path: str = '..\\dataset\\zoom_needle_no_background.csv') -> List[str]:
Нужно убрать значение по умолчанию

2021-11-12 06:17 UTC, redb0 commented on src/contour.py
> +    list_img = pd.DataFrame(pd.read_csv(name_path, sep=";"))
Разве `pd.read_csv` не возвращет `DataFrame`?

2021-11-12 06:17 UTC, redb0 commented on src/contour.py
> +    path_img = '../dataset/' + path_img
Не нужно `'../dataset/'` делать внутри функции. Пусть эта часть будет в `path_img` передаваться.

2021-11-15 09:12 UTC, rondi201 commented on src/linear.py
> +    СЛУЖЕБНЫЙ
Этот класс используется только внутри модуля и я не знаю, как пометить класс как private

2021-11-15 09:59 UTC, rondi201 commented on src/linear.py
> +    def __cross_point_lines(self, line1: Line, line2: Line) -> Tuple[float]:
Класс ContourLine служит для работы с линиями. Поэтому в нём прописанны методы для работы с линиями. Я не понимаю, зачем мне делегировать работу с несколькими линиями классу Line, который отвечает только за одну линию.

2021-11-15 12:22 UTC, redb0 commented on src/linear.py
> +    def __cross_point_lines(self, line1: Line, line2: Line) -> Tuple[float]:
Потому что класс `Line` представляет геометрический объект, который умеет пересекаться с другими линиями, осями и прочим. Так же как и поиск расстояния от линии до другого объекта может быть методом линии. Здесь получается, что класс `ContourLine` должен "знать" как пересекаются объекты, которые он содержит.

В данном случае, пусть будет так.

2021-11-15 12:25 UTC, merged