🐍 Реализация главного окна #33
AAIvanchenko/Diamond-needle-quality pull request #45
Opened 2021-12-05 08:57 UTC by rondi201

Создан .ui файл главного окна.
Создан скрипт для конвертации .ui файла в .py.
Создано главное окно приложения.
Добавлен скрипт для запуска главного окна на основе виртуального 
окружения для anaconda (start.bat).

В приложение добавлены следующие функции:
- выход из приложения;
- загрузка изображения посредством диалогового окна;
- вывод загруженного изображения иглы на экран;
- изменение размера изображения иглы при изменении размера главного 
окна;
- применение выбранных пользователем методов повышения резкости;
- применение выбранных пользователем фильтров нахождения границ;
- нахождение границ иглы и линий, их описывающих;
- нахождение статистических данных по игле;
- создание вердикта об остроте иглы;
- вывод изображения иглы на главный экран с выбранными вариантами 
отображения;
- вывод статистических данных об игле на главный экран.

2021-12-07 14:56 UTC, redb0 requested changes

2021-12-07 14:56 UTC, redb0 commented on src/imageproc.py
> +from typing import Callable
Стоит следовать стандарту. Порядок импортов должен быть следующим: 
- встроенные модули и пакеты
- сторонние
- собственные

Все три группы лучше разделить пустой строкой. Также в каждой группе должны сначала идти строки с командой `import ...`, а затем строки с `from ... import ...`.

Таким образом, нужно `typing` поместить в самый верх, затем `cv2` и потом `matplotlib`.

2021-12-07 14:56 UTC, redb0 commented on src/linear.py
> +    def make_sharping_result(self, needle_height: int, threshold: float = 0.02):
Ремарка. Пробелы вокруг знака равно ставить не нужно при указании значения по умолчанию.

2021-12-07 14:56 UTC, redb0 commented on src/linear.py
> +            self.is_sharp_result = True
Это можно записать в одну строку, без использования `if ... else ...`

2021-12-07 14:56 UTC, redb0 commented on src/linear.py
> +def build_ContourLine(contour: pd.DataFrame,
Используем `snake_case`.

2021-12-07 14:56 UTC, redb0 commented on src/linear.py
> +    IQR = Q3 - Q1
`pylint` не ругается на это? Нужно добавить директивы для игнора `# pylint: disable=invalid-name`

2021-12-07 14:56 UTC, redb0 commented on src/linear.py
> +    df_IQR = df_IQR["y"]
`snake_case`

2021-12-07 14:56 UTC, redb0 commented on src/main.py
> +    """Функция старта программы."""
Это не функция)

2021-12-07 14:56 UTC, redb0 commented on src/mainwindow.py
> +                        "Image Files (*.png *.jpg)")[0]
Как по мне, лучще использовать такое форматирование:

```
file_path = QFileDialog.getOpenFileName(
    self, "Загрузить изображение иглы",
    self.image_directory, "Image Files (*.png *.jpg)"
)[0]
```

2021-12-07 14:56 UTC, redb0 commented on src/mainwindow.py
> +        if file_path == "":
Используем свойства ложных объектов: `not file_path`

2021-12-07 14:56 UTC, redb0 commented on src/mainwindow.py
> +        self.image_directory = "/".join(file_path.split("/")[:-1])
Для работы с путями лучше использовать современные средства по типу встроенной библиотеки `Path` и забыть про строки и индексы как про страшный сон.

2021-12-07 14:56 UTC, redb0 commented on src/mainwindow.py
> +        return home_path
Зачем такие сложности? Можно использовать встроенную библиотеку `Path` и получить домашнюю директорию в одну строку.

2021-12-07 14:56 UTC, redb0 commented on src/mainwindow.py
> +                            bytesPerLine, QImage.Format_RGB888).rgbSwapped()
Такое форматирование не очень. Используем либо, то что указано выше, либо:

```
self.ui_image = QImage(image.data, width, height,
                       bytesPerLine, QImage.Format_RGB888).rgbSwapped()
```

2021-12-07 14:56 UTC, redb0 commented on src/mainwindow.py
> +            raise ValueError("Неверный размер массива изображеия")
Это исключение где-то обрабатывается или программа просто упадет?

2021-12-07 14:56 UTC, redb0 commented on src/mainwindow.py
> +                        self.linear.horizontal_line]:
Может лучше добавить методы `__len__()` и `__getitem__()` или `__iter__()` и `__next__()` в `ContourLine` и не писать здесь все ручками?

2021-12-07 15:15 UTC, redb0 commented
Этот реквекст ни прошел ни одной проверки. Сами сделали, так и придерживайтесь их. Первое, что нужно сделать:
- файлы `ui_*` в игнор, их проверять не нужно
- разобраться с путями для `pylint` ему не нравиться директория `src`. Нужно запускать проверку из этой директории

Там 53 проблемы только от `flake8`. Перед коммитом нужно проверять линтерами! Разве VSCode или PyCharm не ругаются на эти проблемы?

2021-12-19 20:33 UTC, rondi201 commented on src/mainwindow.py
> +        return home_path
Пытался найти, как это сделать. Вы имеете ввиду os.path? Если да, то я не нашёл ничего про это.

2021-12-19 21:24 UTC, merged